---
title: "Diamonds"
author: "Beroy Jenkins"
date: "26/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
install.packages("memisc")
```


```{r}
install.packages('ggplot2', dependencies = T) 
library(ggplot2)
library(GGally)
library(scales)
library(memisc)
library(MASS)
library(car)
library(reshape2)
library(gridExtra)
```
```{r}
install.packages('RColorBrewer', dependencies = TRUE)
library(RColorBrewer)
```



```{r}
data("diamonds")
summary(diamonds$cut[2])

?diamonds
str(diamonds)
```

```{r}
ggplot(aes(x = price), data = diamonds)+
  geom_histogram(binwidth = 1)
```


```{r}
qplot(data = diamonds, x =  price)
```

```{r}
diamonds$price[names(diamonds$price)>500]

as.data.frame(table(diamonds$price >= 15000))
```

```{r}
by(diamonds$price, diamonds$cut, summary)
```

```{r}
ggplot(aes(x = price/carat), data = diamonds)+
  geom_histogram()+
  scale_x_log10()+
  facet_wrap(~cut, scales = "free_y")
```


```{r}
ggplot(aes(x = color, y = price), data = diamonds)+
  geom_boxplot()+
  coord_cartesian(ylim =c(0, 8750))
```


```{r}
by(diamonds$price,diamonds$color,summary)

IQR(subset(diamonds, color =='D')$price)
IQR(subset(diamonds, color == "J")$price) 

```

```{r}
ggplot(aes(x = color, y= price/carat), data = diamonds)+
  geom_boxplot()
```

```{r}
ggplot(aes(x = carat), data = diamonds) +
  geom_freqpoly(aes(color = carat),binwidth = 0.1) + 
  scale_x_continuous(breaks = seq(0,3,0.2)) + 
  scale_y_continuous(breaks=seq(0,16000,2000))+
  xlab('carat')

table(diamonds$carat)

```

```{r}
ggplot(aes(x = carat, y = price), data = diamonds)+
  scale_x_continuous(lim = (c(0,quantile(diamonds$carat, 0.99)) ))+
  scale_y_continuous(lim = (c(0,quantile(diamonds$price, 0.99)) ))+
  geom_point()
```


```{r}
ggplot(aes(x = carat, y = price), data = diamonds)+
  scale_x_continuous(lim = (c(0,quantile(diamonds$carat, 0.99)) ))+
  scale_y_continuous(lim = (c(0,quantile(diamonds$price, 0.99)) ))+
  geom_point()+
  stat_smooth(method = 'lm')

```
```{r}
set.seed(20022012)

diamonds_samp <- diamonds[sample(1:length(diamonds$price),10000),]

test = ggpairs(data = diamonds_samp,
  lower = list(continuous = wrap("points", shape = I('.'))),
  upper = list(combo = wrap("box", outlier.shape = I('.'))),
  axisLabels = 'internal')

print(test)
```




```{r}
plo1 <- ggplot(aes(x =price), data = diamonds)+
  scale_x_continuous(lim = (c(0,quantile(diamonds$price, 0.99)) ))+
  geom_histogram()+
  ggtitle('Price')

plo2 <- ggplot(aes(x = price), data = diamonds)+
  scale_x_log10()+
  geom_histogram()+
  ggtitle('Price log10')

grid.arrange(plo1,plo2)

```


```{r}

plo1 <- ggplot(aes(x = carat, y = price), data = diamonds)+
  scale_y_continuous(trans = log10_trans())+
  geom_point()

plo2 <- ggplot(aes(x = carat, y = price), data = diamonds)+
    scale_y_log10()+
    geom_point()

grid.arrange(plo1,plo2)
```



```{r}
cuberoot_trans <- function() {
  trans_new('cuberrot',
            transform = function(x) x^(1/3),
            inverse = function(x) x^3)
  
}
```


```{r}
ggplot(aes(x = carat, y = price), data = diamonds)+
    scale_x_continuous(trans = cuberoot_trans(), limits = c(0.2,3),breaks = c(0.2,0.5,1,2,3))+
    scale_y_log10(limits = c(350,15000), breaks = c(350,1000,5000,10000,15000))+
    geom_point()
```

```{r}
ggplot(aes(carat, price), data = diamonds) + 
  geom_point(alpha = 0.5, position = 'jitter', size = 3/4) + 
  scale_x_continuous(trans = cuberoot_trans(), limits = c(0.2, 3),
                     breaks = c(0.2, 0.5, 1, 2, 3)) + 
  scale_y_continuous(trans = log10_trans(), limits = c(350, 15000),
                     breaks = c(350, 1000, 5000, 10000, 15000)) +
  ggtitle('Price (log10) by Cube-Root of Carat')
```





```{r}
ggplot(aes(carat, price, color = clarity), data = diamonds) + 
  geom_point(alpha = 0.5, position = 'jitter', size = 3/4) + 
  scale_x_continuous(trans = cuberoot_trans(), limits = c(0.2, 3),
                     breaks = c(0.2, 0.5, 1, 2, 3)) + 
  scale_y_continuous(trans = log10_trans(), limits = c(350, 15000),
                     breaks = c(350, 1000, 5000, 10000, 15000)) +
  scale_color_brewer(type = 'div', guide = guide_legend(title = 'Clarity', reverse = TRUE, override.aes = list(alpha = 1, size = 2)))+
  ggtitle('Price (log10) by Cube-Root of Carat and clarity')
```

```{r}
ggplot(aes(carat, price, color = cut), data = diamonds) + 
  geom_point(alpha = 0.5, position = 'jitter', size = 3/4) + 
  scale_x_continuous(trans = cuberoot_trans(), limits = c(0.2, 3),
                     breaks = c(0.2, 0.5, 1, 2, 3)) + 
  scale_y_continuous(trans = log10_trans(), limits = c(350, 15000),
                     breaks = c(350, 1000, 5000, 10000, 15000)) +
  scale_color_brewer(type = 'div', guide = guide_legend(title = 'Cut', reverse = TRUE, override.aes = list(alpha = 1, size = 2)), palette=('Spectral'))+
  ggtitle('Price (log10) by Cube-Root of Carat and cut')
```

```{r}
ggplot(aes(x = carat, y = price, color =color), data = diamonds) + 
  geom_point(alpha = 0.5, size = 1, position = 'jitter') +
  scale_color_brewer(type = 'div',
                     guide = guide_legend(title = 'Color',
                                          override.aes = list(alpha = 1, size = 2))) +  
  scale_x_continuous(trans = cuberoot_trans(), limits = c(0.2, 3),
                     breaks = c(0.2, 0.5, 1, 2, 3)) + 
  scale_y_continuous(trans = log10_trans(), limits = c(350, 15000),
                     breaks = c(350, 1000, 5000, 10000, 15000)) +
  ggtitle('Price (log10) by Cube-Root of Carat and Color')
```


```{r}
m1 <-  lm(I(log(price)) ~ I(carat^(1/3)), data = diamonds)
m2 <- update(m1, ~ . + carat)
m3 <- update(m2, ~ . + cut)
m4 <- update(m3, ~ . + color)
m5 <- update(m4, ~ . + clarity)

mtable(m1, m2, m3, m4, m5)
```











