---
title: "facething"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
install.packages('ggplot2', dependencies = T) 
library(ggplot2)
```


```{r}
install.packages('gridExtra') 
library(gridExtra)
```

```{r}
install.packages("reshape2")
library(reshape2)
```



```{r}
getwd()
setwd("C:/Users/Avell/OneDrive/Documentos/udacity/br-machine-learning/projects/R")

df_data_face <- read.csv('../Data/pseudo_facebook.tsv', sep = '\t')

```



```{r}
ggplot(data = df_data_face, aes(x = df_data_face$dob_day)) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(breaks = 1:31)+
  facet_wrap(~dob_month)


```




```{r}
ggplot(aes(x = friend_count), data = df_data_face)+
  geom_histogram(binwidth = 30)
```
```{r}
qplot(data = df_data_face, x =  df_data_face$friend_count)
```


```{r}
qplot(data = df_data_face, x =  df_data_face$friend_count, xlim = c(0,1000))
```

```{r}
ggplot(aes(x = friend_count), data = subset(df_data_face, !is.na(gender))) + 
  geom_histogram(binwidth = 10) + 
  scale_x_continuous(limits = c(0, 1000), breaks = seq(0, 1000, 50)) + 
  facet_wrap(~gender)
 

```

```{r}
table(df_data_face$gender)

by(df_data_face$friend_count, df_data_face$gender, summary)

test = by(df_data_face$friend_count, df_data_face$gender, median)

test[1] - test[2]
```

242-165


```{r}
qplot( x = df_data_face$tenure/365, data = df_data_face, binwidth = .25, 
   color = I('black'), fill = I('#099DD9'))+
  scale_x_continuous(breaks = seq(1,7,1), limits = c(0,7))


```





```{r}
qplot( x = df_data_face$age, data = df_data_face, binwidth = 1,
   color = I('black'), fill = I('#099DD9'))
```

 
```{r}
ggplot(aes(x = age), data = df_data_face) + 
  geom_histogram(binwidth = 1, fill = '#5760AB') + 
  scale_x_continuous(breaks = seq(0, 113, 5))
```


```{r}
plot1 <- ggplot(data = df_data_face, aes(x = df_data_face$friend_count)) + 
  geom_histogram(fill = '#5760AB')
plot2 <- ggplot(data = df_data_face, aes(x = log10(df_data_face$friend_count + 1))) + 
  geom_histogram(fill = '#5760AB')
plot3 <- ggplot(data = df_data_face, aes(x = sqrt(df_data_face$friend_count))) + 
  geom_histogram(fill = '#5760AB')

grid.arrange(plot1, plot2, plot3)
               
```

```{r}
ggplot(aes(x = age), data = df_data_face) + 
  geom_histogram(binwidth = 1, fill = '#5760AB')
```

```{r}
ggplot(aes(x = www_likes, y = ..count../sum(..count..)), data = subset(df_data_face, !is.na(gender))) +
  geom_freqpoly(aes(color = gender)) + 
  scale_x_continuous() + 
  scale_x_log10()+
  xlab('likes') + 
  ylab('Percentage of users with likes')
```

```{r}
by(df_data_face$www_likes, df_data_face$gender, sum)
```


```{r}
ggplot(aes(x = gender, y = friend_count), data = subset(df_data_face, !is.na(gender))) + 
  geom_boxplot() +
  coord_cartesian(ylim =c(0, 250))
 
```

```{r}
df_data_face$used_mobile <- ifelse(df_data_face$mobile_likes > 0, 1, 0)
df_data_face$used_mobile <- factor(df_data_face$used_mobile)

length (df_data_face$used_mobile)
summary(df_data_face$used_mobile)[2]/summary(df_data_face$used_mobile,sum())



```
```{r}
ggplot(aes(x = age, y = friend_count), data = df_data_face) +
geom_point()
```

```{r}
ggplot(aes(x = age, y = friend_count), data = df_data_face) +
  geom_point(alpha = 1/20)+
  xlim(13,90)+
  coord_trans(y = 'sqrt')
```
```{r}
ggplot(aes(x = age, y = friendships_initiated), data = df_data_face) +
  geom_point(alpha = 1/25, position = 'jitter')+
  xlim(13,90)
```



```{r}
age_groups <- group_by(df_data_face, age)
df_data_face.fc_by_age <- summarise(age_groups,
          friend_count_man = mean(friend_count),
          friend_count_median = median(friend_count),
          n = n())

df_data_face.fc_by_age <- arrange(df_data_face.fc_by_age, age)


head(df_data_face.fc_by_age)


```


```{r}
df_data_face.fc_by_age <- df_data_face %>%
  group_by(age) %>% 
  summarise(
    friend_count_mean = mean(friend_count),
    friend_count_median = median(friend_count),
    n = n()) %>% 
  arrange(age)
head(df_data_face.fc_by_age)

?n()
```

```{r}
ggplot(aes(x = age, y = friend_count_mean), data = df_data_face.fc_by_age) +
  geom_line(position = 'jitter')
```

```{r}
ggplot(aes(x = age, y = friend_count), data = df_data_face) +
  geom_point(alpha = 1/20, position = position_jitter(height = 0), color='cornflowerblue')+
  coord_trans(y = 'sqrt')+
  coord_cartesian(xlim = c(13, 90))+
  scale_x_continuous(breaks = seq(13,90,5))+
  geom_line(stat = 'summary', fun.y = mean)+
  geom_line(stat = 'summary', fun.y = median, color='red')+
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = .1), linetype = 2)+
  geom_line(stat = 'summary', fun.y = quantile, fun.args = list(probs = .9), linetype = 2)+
  theme_dark() 

```
```{r}
cor.test(df_data_face$age,df_data_face$friend_count)
with(df_data_face,cor.test(df_data_face$age,df_data_face$friend_count) )
with(subset(df_data_face, age<=70),cor.test(age,friend_count))
```

```{r}
ggplot(aes(x = www_likes_received, y = likes_received), data = df_data_face) +
  geom_point(alpha = 1/20, position = position_jitter(height = 0), color='red')+
  coord_cartesian(xlim = c(0, quantile(df_data_face$www_likes_received, 0.95)),ylim = c(0,quantile(df_data_face$likes_received, 0.95)))+
  geom_smooth(method = "lm")+
  theme_dark() 

```
```{r}
with(df_data_face,cor.test(www_likes_received,likes_received))

```

```{r}
df_data_face$age_with_months <- df_data_face$age + (1 - df_data_face$dob_month / 12)

df_data_face$age_with_months <- df_data_face$age + (12 - df_data_face$dob_month) / 12

head(df_data_face$age_with_months)
head(df_data_face)


```


```{r}
df_data_face.fc_by_age_month <- df_data_face %>%
  group_by(age_with_months) %>% 
  summarise(
    friend_count_mean = mean(friend_count),
    friend_count_median = median(friend_count),
    n = n()) %>% 
  arrange(age_with_months)
head(df_data_face.fc_by_age_month)

```
```{r}
ggplot(aes(x = age_with_months, y = friend_count_mean), data = subset(df_data_face.fc_by_age_month, age_with_months < 71)) +
  geom_point(position = position_jitter(height = 0), color='red')+
  theme_dark() 



```

```{r}
df_data_face.fc_by_age_gender <- df_data_face %>%
  filter(!is.na(gender)) %>% 
  group_by(age, gender) %>% 
  summarise(
    mean_friend_count = mean(friend_count),
    median_friend_count = median(friend_count),
    n = n()) %>% 
  ungroup() %>% 
  arrange(age)
head(df_data_face.fc_by_age_gender)
```


```{r}
ggplot(aes(x = age, y = median_friend_count, color = gender), data = df_data_face.fc_by_age_gender) +
  geom_line(position = 'jitter',stat = "summary", fun.y = median)+
    theme_dark() 

```




```{r}
df_data_face.fc_by_age_gender.wide <- dcast(df_data_face.fc_by_age_gender,
                                            age ~ gender,
                                            value.var = 'median_friend_count')

head(df_data_face.fc_by_age_gender.wide)

```
tbm possivel 
pf.fc_by_age_gender.wide <-     subset(pf.fc_by_age_gender[c('age', 'gender', 'median_friend_count')],
                                        !is.na(gender)) %>%
    spread(gender, median_friend_count) %>%
    mutate(ratio = male / female)

head(pf.fc_by_age_gender.wide)

```{r}
ggplot(data = df_data_face.fc_by_age_gender.wide, aes(x = age, y = female / male))+
  geom_line()+
  geom_hline(yintercept = 1,alpha = 0.3, linetype = 2)
```



```{r}
df_data_face$year_joined <- floor(2014 - df_data_face$tenure/365)
```

```{r}
df_data_face$year_joined.bucket <- cut (df_data_face$year_joined, c(2004, 2009, 2011, 2012, 2014))

table(df_data_face$year_joined.bucket, useNA = "ifany")
```

```{r}
ggplot(aes(x = age, y = friend_count),
              data = subset(df_data_face, !is.na(gender))) +
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)
```
# As a reminder, the parameter linetype can take the values 0-6:

# 0 = blank, 1 = solid, 2 = dashed
# 3 = dotted, 4 = dotdash, 5 = longdash
# 6 = twodash

```{r}
ggplot(aes(x = age, y = friend_count),
              data = subset(df_data_face, !is.na(gender))) +
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = mean)+
  geom_line(stat = 'summary', fun.y = mean, linetype = 6)
```

```{r}
with(subset(df_data_face, tenure >= 1), summary(friend_count/tenure))
```



```{r}
ggplot(aes(x = tenure, y = friendships_initiated/tenure),
              data = subset(df_data_face, tenure >= 1)) +
  geom_smooth(aes(color = year_joined.bucket))
```





